package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/goccy/go-yaml"
)

type document struct {
	Components struct {
		Schemas map[string]schema `yaml:"schemas"`
	} `yaml:"components"`
}

type schema map[string]any

func main() {
	root := findRepoRoot()
	input := filepath.Join(root, "docs", "openapi", "openapi.yaml")
	output := filepath.Join(root, "frontend", "src", "lib", "generated", "openapi-types.ts")
	if len(os.Args) == 3 {
		input = os.Args[1]
		output = os.Args[2]
	}

	raw, err := os.ReadFile(input)
	if err != nil {
		fatalf("read openapi: %v", err)
	}

	var doc document
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fatalf("parse openapi: %v", err)
	}
	if len(doc.Components.Schemas) == 0 {
		fatalf("openapi has no component schemas")
	}

	var buf bytes.Buffer
	buf.WriteString("// Generated by `go -C backend run ./cmd/openapi-types`. Do not edit by hand.\n")
	buf.WriteString("// Source: docs/openapi/openapi.yaml\n\n")

	names := make([]string, 0, len(doc.Components.Schemas))
	for name := range doc.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		writeSchema(&buf, name, doc.Components.Schemas[name])
		buf.WriteByte('\n')
	}

	if err := os.MkdirAll(filepath.Dir(output), 0755); err != nil {
		fatalf("create output dir: %v", err)
	}
	if err := os.WriteFile(output, buf.Bytes(), 0644); err != nil {
		fatalf("write types: %v", err)
	}
}

func writeSchema(buf *bytes.Buffer, name string, s schema) {
	if allOf, ok := s["allOf"].([]any); ok && len(allOf) > 0 {
		parts := make([]string, 0, len(allOf))
		for _, item := range allOf {
			parts = append(parts, typeFor(item))
		}
		fmt.Fprintf(buf, "export type %s = %s\n", name, strings.Join(parts, " & "))
		return
	}

	if typ, _ := s["type"].(string); typ == "object" || s["properties"] != nil {
		properties, _ := s["properties"].(map[string]any)
		required := requiredSet(s)
		if len(properties) == 0 {
			fmt.Fprintf(buf, "export type %s = Record<string, unknown>\n", name)
			return
		}
		fmt.Fprintf(buf, "export interface %s {\n", name)
		keys := make([]string, 0, len(properties))
		for key := range properties {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		for _, key := range keys {
			optional := "?"
			if required[key] {
				optional = ""
			}
			fmt.Fprintf(buf, "  %s%s: %s\n", propertyName(key), optional, typeFor(properties[key]))
		}
		if s["additionalProperties"] == true {
			buf.WriteString("  [key: string]: unknown\n")
		}
		buf.WriteString("}\n")
		return
	}

	fmt.Fprintf(buf, "export type %s = %s\n", name, typeFor(s))
}

func typeFor(value any) string {
	if typed, ok := value.(schema); ok {
		value = map[string]any(typed)
	}
	s, ok := value.(map[string]any)
	if !ok {
		return "unknown"
	}
	if ref, ok := s["$ref"].(string); ok {
		return strings.TrimPrefix(ref, "#/components/schemas/")
	}
	if allOf, ok := s["allOf"].([]any); ok && len(allOf) > 0 {
		parts := make([]string, 0, len(allOf))
		for _, item := range allOf {
			parts = append(parts, typeFor(item))
		}
		return strings.Join(parts, " & ")
	}
	switch s["type"] {
	case "string":
		return "string"
	case "integer", "number":
		return "number"
	case "boolean":
		return "boolean"
	case "array":
		return typeFor(s["items"]) + "[]"
	case "object":
		properties, _ := s["properties"].(map[string]any)
		if len(properties) == 0 {
			if additional, ok := s["additionalProperties"].(map[string]any); ok {
				return "Record<string, " + typeFor(additional) + ">"
			}
			return "Record<string, unknown>"
		}
		required := requiredSet(s)
		keys := make([]string, 0, len(properties))
		for key := range properties {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, key := range keys {
			optional := "?"
			if required[key] {
				optional = ""
			}
			parts = append(parts, fmt.Sprintf("%s%s: %s", propertyName(key), optional, typeFor(properties[key])))
		}
		return "{ " + strings.Join(parts, "; ") + " }"
	default:
		return "unknown"
	}
}

func requiredSet(s map[string]any) map[string]bool {
	required := map[string]bool{}
	values, _ := s["required"].([]any)
	for _, value := range values {
		if key, ok := value.(string); ok {
			required[key] = true
		}
	}
	return required
}

func propertyName(value string) string {
	if value == "" {
		return `""`
	}
	for i, r := range value {
		if !(r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')) {
			return fmt.Sprintf("%q", value)
		}
	}
	return value
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}

func findRepoRoot() string {
	cwd, err := os.Getwd()
	if err != nil {
		fatalf("get working directory: %v", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(cwd, "docs", "openapi", "openapi.yaml")); err == nil {
			return cwd
		}
		parent := filepath.Dir(cwd)
		if parent == cwd {
			fatalf("could not find repo root containing docs/openapi/openapi.yaml")
		}
		cwd = parent
	}
}
