-- +goose Up
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT,
  password_hash TEXT,
  nickname TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('student', 'parent', 'teacher', 'counselor', 'admin')),
  province TEXT NOT NULL DEFAULT '',
  grade TEXT NOT NULL DEFAULT '',
  is_shadow BOOLEAN NOT NULL DEFAULT false,
  banned_at TIMESTAMPTZ,
  banned_reason TEXT NOT NULL DEFAULT '',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_users_email_unique ON users (lower(email)) WHERE deleted_at IS NULL AND email IS NOT NULL;
CREATE UNIQUE INDEX idx_users_nickname_active ON users (nickname) WHERE deleted_at IS NULL;

CREATE TABLE auth_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ
);

CREATE INDEX idx_auth_sessions_user_active ON auth_sessions (user_id, expires_at) WHERE revoked_at IS NULL;

CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  author_name TEXT NOT NULL,
  author_role TEXT NOT NULL,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  track TEXT NOT NULL CHECK (track IN ('physics', 'history')),
  electives JSONB NOT NULL DEFAULT '[]'::jsonb,
  category TEXT NOT NULL CHECK (category IN ('experience', 'question', 'data')),
  grade TEXT NOT NULL,
  province TEXT NOT NULL,
  likes_count INTEGER NOT NULL DEFAULT 0 CHECK (likes_count >= 0),
  comments_count INTEGER NOT NULL DEFAULT 0 CHECK (comments_count >= 0),
  favorites_count INTEGER NOT NULL DEFAULT 0 CHECK (favorites_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  search_vector TSVECTOR NOT NULL DEFAULT ''::tsvector
);

-- +goose StatementBegin
CREATE FUNCTION update_posts_search_vector() RETURNS trigger AS $$
BEGIN
  NEW.search_vector :=
    setweight(to_tsvector('simple', coalesce(NEW.title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(NEW.content, '')), 'B') ||
    setweight(to_tsvector('simple', coalesce(NEW.author_name, '') || ' ' || coalesce(NEW.province, '') || ' ' || coalesce(NEW.grade, '') || ' ' || coalesce(NEW.tags::text, '') || ' ' || coalesce(NEW.electives::text, '')), 'C');
  RETURN NEW;
END
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_posts_search_vector
BEFORE INSERT OR UPDATE OF title, content, author_name, province, grade, tags, electives
ON posts
FOR EACH ROW
EXECUTE FUNCTION update_posts_search_vector();

CREATE INDEX idx_posts_latest_cursor ON posts (created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_feed ON posts (track, category, province, created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_author ON posts (author_name) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_user ON posts (user_id, created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_tags_gin ON posts USING GIN (tags jsonb_path_ops);
CREATE INDEX idx_posts_search_gin ON posts USING GIN (search_vector);

CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  author TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_comments_post ON comments (post_id, created_at ASC, id ASC) WHERE deleted_at IS NULL;

CREATE TABLE post_likes (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE post_favorites (
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE follows (
  follower_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (follower_id, author_name)
);

CREATE TABLE user_profiles (
  user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  bio TEXT NOT NULL DEFAULT '',
  choice_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  target_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ
);

CREATE INDEX idx_notifications_cursor ON notifications (recipient_user_id, created_at DESC, id DESC);
CREATE INDEX idx_notifications_unread ON notifications (recipient_user_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE direct_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (length(content) <= 2000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at TIMESTAMPTZ
);

CREATE INDEX idx_direct_messages_pair_sender ON direct_messages (sender_user_id, recipient_user_id, created_at DESC, id DESC);
CREATE INDEX idx_direct_messages_pair_recipient ON direct_messages (recipient_user_id, sender_user_id, created_at DESC, id DESC);
CREATE INDEX idx_direct_messages_unread ON direct_messages (recipient_user_id, sender_user_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  topic_tag TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  views_count INTEGER NOT NULL DEFAULT 0 CHECK (views_count >= 0),
  posts_count INTEGER NOT NULL DEFAULT 0 CHECK (posts_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE topic_posts (
  topic_id BIGINT NOT NULL REFERENCES topics(id) ON DELETE CASCADE,
  post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
  PRIMARY KEY (topic_id, post_id)
);

CREATE TABLE email_verification_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at TIMESTAMPTZ,
  failed_attempts INTEGER NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_email_verification_lookup ON email_verification_codes (email, used_at, expires_at, created_at DESC);

CREATE TABLE email_verification_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  client_ip INET NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_email_verification_attempts_email ON email_verification_attempts (email, created_at DESC);
CREATE INDEX idx_email_verification_attempts_ip ON email_verification_attempts (client_ip, created_at DESC);

CREATE TABLE upload_assets (
  id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  asset_key TEXT NOT NULL UNIQUE,
  file_name TEXT NOT NULL,
  content_type TEXT NOT NULL,
  ext TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  width INTEGER NOT NULL CHECK (width > 0),
  height INTEGER NOT NULL CHECK (height > 0),
  status TEXT NOT NULL CHECK (status IN ('pending', 'completed', 'expired', 'failed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  completed_at TIMESTAMPTZ
);

CREATE INDEX idx_upload_assets_user_status ON upload_assets (user_id, status, created_at DESC);
CREATE INDEX idx_upload_assets_pending_expiry ON upload_assets (expires_at) WHERE status = 'pending';

CREATE TABLE admin_content_records (
  id TEXT PRIMARY KEY,
  module TEXT NOT NULL,
  title TEXT NOT NULL,
  content_type TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '草稿',
  scope TEXT NOT NULL DEFAULT '全国',
  owner TEXT NOT NULL DEFAULT '',
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  summary TEXT NOT NULL DEFAULT '',
  url TEXT NOT NULL DEFAULT '',
  priority TEXT NOT NULL DEFAULT '常规',
  sort_order INTEGER NOT NULL DEFAULT 0,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX idx_admin_content_listing ON admin_content_records (module, status, sort_order, updated_at DESC) WHERE deleted_at IS NULL;

CREATE TABLE admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  record_id TEXT,
  module TEXT,
  detail TEXT NOT NULL DEFAULT '',
  actor TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_audit_created ON admin_audit_logs (created_at DESC, id DESC);

CREATE TABLE content_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL UNIQUE REFERENCES posts(id) ON DELETE CASCADE,
  source_platform TEXT NOT NULL,
  source_url TEXT NOT NULL UNIQUE,
  source_note_id TEXT NOT NULL DEFAULT '',
  source_title TEXT NOT NULL DEFAULT '',
  source_author TEXT NOT NULL DEFAULT '',
  source_avatar_url TEXT NOT NULL DEFAULT '',
  source_likes INTEGER NOT NULL DEFAULT 0 CHECK (source_likes >= 0),
  source_comments INTEGER NOT NULL DEFAULT 0 CHECK (source_comments >= 0),
  source_favorites INTEGER NOT NULL DEFAULT 0 CHECK (source_favorites >= 0),
  source_format TEXT NOT NULL DEFAULT '图文',
  transformation_note TEXT NOT NULL DEFAULT '',
  captured_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE content_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL,
  target_id BIGINT NOT NULL,
  reason TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open',
  resolution_note TEXT NOT NULL DEFAULT '',
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (reporter_user_id, target_type, target_id)
);

CREATE INDEX idx_content_reports_status ON content_reports (status, created_at DESC, id DESC);

CREATE TABLE subject_insights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  combination TEXT NOT NULL UNIQUE,
  trend TEXT NOT NULL,
  heat INTEGER NOT NULL CHECK (heat >= 0),
  match_rate NUMERIC(10, 6) NOT NULL CHECK (match_rate >= 0),
  advice TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT '',
  metric_type TEXT NOT NULL DEFAULT '',
  unit TEXT NOT NULL DEFAULT '',
  province TEXT NOT NULL DEFAULT '',
  data_year INTEGER NOT NULL DEFAULT 0,
  source_name TEXT NOT NULL DEFAULT '',
  source_url TEXT NOT NULL DEFAULT '',
  scope TEXT NOT NULL DEFAULT '',
  sample_size INTEGER NOT NULL DEFAULT 0,
  captured_at TIMESTAMPTZ,
  methodology TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE provinces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  region TEXT NOT NULL DEFAULT '',
  coverage_status TEXT NOT NULL CHECK (coverage_status IN ('verified', 'unverified')),
  data_year INTEGER NOT NULL,
  records_count INTEGER NOT NULL DEFAULT 0 CHECK (records_count >= 0),
  captured_at TIMESTAMPTZ NOT NULL,
  methodology TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sources (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  province_id BIGINT REFERENCES provinces(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  asset_key TEXT,
  file_hash TEXT NOT NULL,
  data_year INTEGER NOT NULL,
  scope TEXT NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  methodology TEXT NOT NULL,
  coverage_status TEXT NOT NULL CHECK (coverage_status IN ('verified', 'unverified')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_sources_file_hash ON sources (file_hash) WHERE file_hash <> '';
CREATE INDEX idx_sources_province_year ON sources (province_id, data_year DESC, captured_at DESC);

CREATE TABLE policies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  province_id BIGINT REFERENCES provinces(id) ON DELETE SET NULL,
  source_id UUID NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  scope TEXT NOT NULL,
  coverage_status TEXT NOT NULL CHECK (coverage_status IN ('verified', 'unverified')),
  data_year INTEGER NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  methodology TEXT NOT NULL,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  url TEXT NOT NULL DEFAULT '',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_policies_listing ON policies (coverage_status, scope, data_year DESC, captured_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_policies_tags_gin ON policies USING GIN (tags jsonb_path_ops);

CREATE TABLE requirements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  province_id BIGINT REFERENCES provinces(id) ON DELETE SET NULL,
  source_id UUID NOT NULL REFERENCES sources(id) ON DELETE RESTRICT,
  title TEXT NOT NULL,
  major_code TEXT NOT NULL DEFAULT '',
  type TEXT NOT NULL,
  scope TEXT NOT NULL,
  required_subjects JSONB NOT NULL DEFAULT '[]'::jsonb,
  coverage_status TEXT NOT NULL CHECK (coverage_status IN ('verified', 'unverified')),
  data_year INTEGER NOT NULL,
  captured_at TIMESTAMPTZ NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  methodology TEXT NOT NULL,
  tags JSONB NOT NULL DEFAULT '[]'::jsonb,
  url TEXT NOT NULL DEFAULT '',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_requirements_listing ON requirements (coverage_status, scope, data_year DESC, captured_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_requirements_title ON requirements (title);
CREATE INDEX idx_requirements_subjects_gin ON requirements USING GIN (required_subjects jsonb_path_ops);
CREATE INDEX idx_requirements_tags_gin ON requirements USING GIN (tags jsonb_path_ops);

CREATE TABLE media_assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  source_id UUID REFERENCES sources(id) ON DELETE SET NULL,
  asset_key TEXT NOT NULL UNIQUE,
  variant TEXT NOT NULL DEFAULT 'original',
  content_type TEXT NOT NULL,
  size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
  width INTEGER CHECK (width IS NULL OR width > 0),
  height INTEGER CHECK (height IS NULL OR height > 0),
  file_hash TEXT NOT NULL DEFAULT '',
  visibility TEXT NOT NULL CHECK (visibility IN ('public', 'private')),
  status TEXT NOT NULL CHECK (status IN ('pending', 'ready', 'failed', 'deleted')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_media_assets_owner ON media_assets (owner_user_id, created_at DESC);
CREATE INDEX idx_media_assets_source ON media_assets (source_id, created_at DESC);

CREATE TABLE import_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_name TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  row_counts JSONB NOT NULL DEFAULT '{}'::jsonb,
  sha256_manifest JSONB NOT NULL DEFAULT '[]'::jsonb,
  error_message TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT 'system'
);

-- +goose Down
DROP TABLE IF EXISTS import_runs;
DROP TABLE IF EXISTS media_assets;
DROP TABLE IF EXISTS requirements;
DROP TABLE IF EXISTS policies;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS provinces;
DROP TABLE IF EXISTS subject_insights;
DROP TABLE IF EXISTS content_reports;
DROP TABLE IF EXISTS content_sources;
DROP TABLE IF EXISTS admin_audit_logs;
DROP TABLE IF EXISTS admin_content_records;
DROP TABLE IF EXISTS upload_assets;
DROP TABLE IF EXISTS email_verification_attempts;
DROP TABLE IF EXISTS email_verification_codes;
DROP TABLE IF EXISTS topic_posts;
DROP TABLE IF EXISTS topics;
DROP TABLE IF EXISTS direct_messages;
DROP TABLE IF EXISTS notifications;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS post_favorites;
DROP TABLE IF EXISTS post_likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS posts;
DROP FUNCTION IF EXISTS update_posts_search_vector();
DROP TABLE IF EXISTS auth_sessions;
DROP TABLE IF EXISTS users;
