location = /.well-known/assetlinks.json {
    alias /www/wwwroot/Soulcourse/.well-known/assetlinks.json;
    default_type application/json;
    add_header Cache-Control "public, max-age=300";
}

location /downloads/android/ {
    alias /www/wwwroot/Soulcourse/downloads/android/;
    default_type application/octet-stream;
    add_header Cache-Control "public, max-age=300";
}
