export interface AdviceNote {
  id: string
  title: string
  combination: string
  author: string
  role: string
  cover: 'mint' | 'blue' | 'amber' | 'rose' | 'violet'
  lens: 'coverage' | 'pressure' | 'risk' | 'timeline' | 'parent'
  metric: string
  metricLabel: string
  summary: string
  tags: string[]
  actions: string[]
  source: string
  sourceUrl: string
  likes: number
  saves: number
  comments: number
}

export const adviceNotes: AdviceNote[] = [
  {
    id: 'phy-chem-bio-coverage',
    title: '物化生不是万能答案，先看你能不能长期稳定投入',
    combination: '物理 + 化学 + 生物',
    author: '选科研究所',
    role: '规划师认证',
    cover: 'mint',
    lens: 'coverage',
    metric: '91.5%',
    metricLabel: '匹配参考',
    summary: '适合目标仍在理工、医学、农学、生命科学间摇摆，且三科最近三次校内排名较稳定的学生。真正的门槛不是“覆盖率高”，而是物理模型、化学体系、生物细节记忆都要持续投入。',
    tags: ['专业覆盖', '医学工科', '收藏核对'],
    actions: ['用目标专业逐条查本省选考目录', '记录物理和化学错题修复速度', '不要用生物兴趣掩盖化学压力'],
    source: '阳光高考选考科目要求汇总',
    sourceUrl: 'https://gaokao.chsi.com.cn/gkxx/zc/ss/202201/20220105/2155365943.html',
    likes: 1820,
    saves: 1460,
    comments: 216,
  },
  {
    id: 'history-politics-geography',
    title: '史政地的优势不是轻松，而是路径清楚',
    combination: '历史 + 政治 + 地理',
    author: '人文升学笔记',
    role: '学长学姐认证',
    cover: 'amber',
    lens: 'risk',
    metric: '73.1%',
    metricLabel: '匹配参考',
    summary: '适合对法学、公共管理、新闻传播、师范、人文社科方向有明确兴趣的学生。政治和地理都不是短期背诵型科目，稳定输出需要材料分析、时政积累和图表训练。',
    tags: ['人文社科', '法学', '材料分析'],
    actions: ['列出目标专业是否真的不限选科', '每周固定做材料题复盘', '提前看大学专业课程而不是只看名字'],
    source: '多省本科专业选考科目要求目录',
    sourceUrl: 'https://gaokao.chsi.com.cn/zyck/',
    likes: 1432,
    saves: 980,
    comments: 188,
  },
  {
    id: 'phy-chem-geo-engineering',
    title: '物化地适合“看图表不头疼”的理科生',
    combination: '物理 + 化学 + 地理',
    author: '地理赋分观察',
    role: '教师认证',
    cover: 'blue',
    lens: 'pressure',
    metric: '84.2%',
    metricLabel: '匹配参考',
    summary: '物化地保留较多工科和理科路径，地理在很多省份兼具理解、记忆和图表分析。适合物理化学较稳，同时不想把第三科放在纯记忆压力上的学生。',
    tags: ['工科友好', '地理赋分', '图表能力'],
    actions: ['看本省地理赋分人数结构', '用目标专业查是否同时卡化学', '比较地理和生物近三次排名波动'],
    source: '省级考试院选考目录与公开问答',
    sourceUrl: 'https://www.jseea.cn/webfile/index/index_zkxx/2022-01-18/27031.html',
    likes: 1268,
    saves: 744,
    comments: 132,
  },
  {
    id: 'phy-bio-geo-risk',
    title: '物生地压力均衡，但最怕目标专业突然卡化学',
    combination: '物理 + 生物 + 地理',
    author: '目标专业核对员',
    role: '规划师认证',
    cover: 'rose',
    lens: 'risk',
    metric: '78.4%',
    metricLabel: '匹配参考',
    summary: '适合想保留一部分理工路径、但化学长期拖后腿的学生。风险在于医学、药学、化工、材料等方向很可能需要化学，必须在高一就把目标专业清单查清。',
    tags: ['避坑核对', '少化学', '目标专业'],
    actions: ['列出 10 个最可能目标专业', '逐条标注是否要求化学', '保留转向人文/管理的备选路径'],
    source: '阳光高考专业选考要求与省级目录',
    sourceUrl: 'https://gaokao.chsi.com.cn/gkxx/zc/ss/202201/20220105/2155365943.html',
    likes: 1090,
    saves: 920,
    comments: 245,
  },
  {
    id: 'history-bio-geography',
    title: '史生地适合兴趣广，但要接受专业边界',
    combination: '历史 + 生物 + 地理',
    author: '家长共读小组',
    role: '家长认证',
    cover: 'violet',
    lens: 'parent',
    metric: '68%',
    metricLabel: '边界提醒',
    summary: '史生地常见于不想选政治、又对生物地理有兴趣的学生。它的体验可能不错，但医学、工科等强限制方向基本要提前放弃或认真核对。',
    tags: ['家长视角', '兴趣稳定', '专业边界'],
    actions: ['和孩子确认“不选物化”的代价', '用专业库先排除明显不匹配方向', '把兴趣学科和职业路径分开讨论'],
    source: '阳光志愿专业信息与省级选考目录',
    sourceUrl: 'https://gaokao.chsi.com.cn/zyck/',
    likes: 884,
    saves: 660,
    comments: 118,
  },
  {
    id: 'timeline-grade-one',
    title: '高一选科时间线：别等到分班前一周才查目录',
    combination: '全部组合',
    author: '高一班主任手记',
    role: '教师认证',
    cover: 'mint',
    lens: 'timeline',
    metric: '4步',
    metricLabel: '决策流程',
    summary: '先排除硬性不适配，再比较学科稳定性，最后结合目标专业和本省赋分。最容易踩坑的是只听“热门组合”，没有做自己的成绩和兴趣证据。',
    tags: ['时间线', '分班前', '决策流程'],
    actions: ['第 1 周列专业兴趣清单', '第 2 周查选考目录', '第 3 周比较三次成绩波动', '第 4 周和老师复盘组合'],
    source: '阳光高考招生政策及省级考试院信息',
    sourceUrl: 'https://gaokao.chsi.com.cn/z/gkbmfslq/zszc.jsp',
    likes: 2011,
    saves: 1884,
    comments: 306,
  },
  {
    id: 'chemistry-importance',
    title: '为什么很多理工专业越来越绕不开化学',
    combination: '物理 + 化学 + X',
    author: '数据观察员',
    role: '规划师认证',
    cover: 'blue',
    lens: 'coverage',
    metric: '高频',
    metricLabel: '目录关键词',
    summary: '材料、化工、能源、环境、医学、药学、食品、生物工程等方向都可能把化学作为基础门槛。化学弱不是不能选，而是要知道自己会失去哪些专业组。',
    tags: ['化学门槛', '理工专业', '目录核对'],
    actions: ['查目标专业是否含化学要求', '区分“喜欢实验”和“能刷体系题”', '用月考排名评估可持续性'],
    source: '教育部选考科目指引与公开选考目录',
    sourceUrl: 'https://gaokao.chsi.com.cn/gkxx/zc/ss/202201/20220105/2155365943.html',
    likes: 1714,
    saves: 1501,
    comments: 198,
  },
  {
    id: 'law-major-path',
    title: '想学法学，政治是不是必须选？',
    combination: '历史 + 政治 + 地理',
    author: '法学学姐答疑',
    role: '学长学姐认证',
    cover: 'amber',
    lens: 'risk',
    metric: '非必须',
    metricLabel: '但有帮助',
    summary: '不少法学专业不限选科，但政治能帮助建立时政、制度和材料分析语感。真正决定后续体验的是阅读量、写作训练和逻辑表达。',
    tags: ['法学', '政治', '不限选科'],
    actions: ['用目标院校核对选科限制', '每周读一篇法治新闻评论', '练习材料题结构化表达'],
    source: '阳光志愿专业信息与高校专业目录',
    sourceUrl: 'https://gaokao.chsi.com.cn/zyck/',
    likes: 1195,
    saves: 702,
    comments: 154,
  },
  {
    id: 'computer-not-only-code',
    title: '计算机不是“会写代码就行”，物理和数学才是底盘',
    combination: '物理 + 化学 + 地理',
    author: '工科过来人',
    role: '学长学姐认证',
    cover: 'violet',
    lens: 'pressure',
    metric: '高压',
    metricLabel: '学习强度',
    summary: '计算机热门不等于轻松。算法、系统、硬件、网络安全等方向都需要数学抽象和工程耐心，选科阶段要先确认物理学习是否能稳定推进。',
    tags: ['计算机', '物化要求', '学习强度'],
    actions: ['看数学和物理错题类型', '确认是否接受长期抽象训练', '不要只被就业热度带走'],
    source: '普通高校本科专业选考科目要求目录',
    sourceUrl: 'https://gaokao.chsi.com.cn/gkxx/zc/ss/202201/20220105/2155365943.html',
    likes: 2260,
    saves: 1740,
    comments: 390,
  },
  {
    id: 'parents-communication',
    title: '家长别只问“哪个组合好就业”，先问孩子能不能学下去',
    combination: '亲子沟通',
    author: '升学家庭观察',
    role: '家长认证',
    cover: 'rose',
    lens: 'parent',
    metric: '3问',
    metricLabel: '沟通模板',
    summary: '选科不是家长替孩子买保险。更有效的问题是：哪科错题能修复？哪类职业愿意了解？哪种压力会让你失控？',
    tags: ['家长提问', '沟通模板', '长期决策'],
    actions: ['先听孩子讲最近一次考试', '把专业信息打印出来一起划重点', '设一个两周后复盘的时间点'],
    source: '人民网教育评论与升学政策公开信息',
    sourceUrl: 'https://edu.people.com.cn/n1/2024/0625/c1006-40263454.html',
    likes: 1566,
    saves: 1312,
    comments: 266,
  },
  {
    id: 'province-difference',
    title: '同一个专业，不同省份目录可能让你做出不同选择',
    combination: '省份核对',
    author: '政策库编辑',
    role: '平台编辑',
    cover: 'blue',
    lens: 'risk',
    metric: '必查',
    metricLabel: '省级目录',
    summary: '不要拿外省经验直接套本省。选科要求、赋分结构、招生批次和专业组设置都可能影响最终选择。',
    tags: ['省份差异', '官方入口', '逐校核对'],
    actions: ['先看本省考试院入口', '再查阳光高考汇总', '最后核对目标院校招生章程'],
    source: '阳光高考与省级教育考试院',
    sourceUrl: 'https://gaokao.chsi.com.cn/z/gkbmfslq/zszc.jsp',
    likes: 1345,
    saves: 1208,
    comments: 149,
  },
  {
    id: 'mbti-not-decision',
    title: 'MBTI 可以辅助聊天，不能替代选科证据',
    combination: '画像工具',
    author: '生涯规划师小陈',
    role: '规划师认证',
    cover: 'mint',
    lens: 'pressure',
    metric: '辅助',
    metricLabel: '不是结论',
    summary: 'MBTI、霍兰德可以帮你描述偏好，但选科还要回到成绩稳定性、专业门槛、学习投入和家庭资源。不要让一个人格标签替你做决定。',
    tags: ['MBTI', '霍兰德', '个人画像'],
    actions: ['把测评结果转成“学习行为”描述', '用成绩波动验证偏好', '找老师核对学科潜力'],
    source: '平台生涯规划方法论与公开专业信息',
    sourceUrl: 'https://gaokao.chsi.com.cn/zyck/',
    likes: 1010,
    saves: 803,
    comments: 121,
  },
]
